# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'OmarBlacck-subscription(dc3f1b56-b638-469f-a845-bef5c3cf2a72)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # First create a resource group
      az group create --name DemoKubGroup --location eastus
      
      # Now create the AKS cluster and enable the cluster autoscaler
      az aks create \
        --resource-group DemoKubGroup\
        --name myAKSCluster \
        --node-count 1 \
        --vm-set-type VirtualMachineScaleSets \
        --load-balancer-sku standard \
        --enable-cluster-autoscaler \
        --min-count 1 \
        --max-count 3
    addSpnToEnvironment: true
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
